### PR TITLE
M1 node lookup

### PR DESCRIPTION
**Pull request by Grumme2**

### CODE REVIEW

**Comment by Grumme2** [comment]
@Kevintrf  och @Hammarkvast  nu är den uppdaterad

**Review by Hammarkvast — APPROVED** [review]
Very nice!

**Review by Kevintrf — CHANGES_REQUESTED** [review]
Bucket.go
- "removeFromBucket" already exists as RemoveContact in the master branch, remove this and use the already existing RemoveContact wherever you used removeFromBucket

Contact.go
- What is the purpose of "Kademlia *Kademlia" in the struct? Is it needed or used? If so for what?

Kademlia.go
- You have renamed "rt RoutingTable" to "Rt RoutingTable" with a capital R in the struct. This is wrong. Also change it to a lowercase rt where you have used rt in your code.

Network.go
- "Address, Id and Kadem" fields in struct. What are these for?
- Using uppcase Rt when refering to RoutingTable (see previous point in kademlia.go)

**Review by Kevintrf — APPROVED** [review]
Looks good, merging

**Pull request merged**
