### PR TITLE
Lookup value done?

### PR DESCRIPTION
**Pull request by Grumme2**
Jag löste problemet jag hade på ett fult sätt med global variabel så godkänn bara om ni tycker att fulhack är ok

### CODE REVIEW

**Review by Hammarkvast — APPROVED** [review]
Seems somewhat legit, but then again, im not sure.

**Review by Kevintrf — CHANGES_REQUESTED** [review]
- The global variables are saved in the node that the findValueRPC is sent to, not the one that sends it. Therefore nothing is returned through network.SendFindDataMessage().

- There are no cases for handling responseType "DATA NOT FOUND" and "DATA FOUND".

- I recommend creating responseType "FINDVALUE_RESPONSE" which has it's data containing a boolean for if the data was found as well as a string for the data. This responseType should be send back to the sender when the listener receives a FINDVALUE message. The case for "FINDVALUE_RESPONSE" in the listener will then place those values in the global variables. (I recommend that you create a struct for this, probably works either way but will make the code more structured). Then after the findValueRPC has been sent from LookupData you can sleep the thread for x amount of time and then read the results from SendFindDataMessage(). 
  -  In order to speed up the thread sleeping you can sleep for small time intervals and check if the global variables have been updated and then continue sleeping for a small time if it hasn't been updated, repeating this until x amount of time has passed which means we have to time out and assume we will not get a response due to some network error.

**Comment by Kevintrf** [comment]
Made some redesigns based on my previous post. I haven't tried it at all besides making sure it actually compiles. So we'll need to go through this carefully and see if all individual parts actually work. Please provide feedback on my commits.

**Comment by Grumme2** [comment]
I think it looks good!

**Review by Hammarkvast — APPROVED** [review]
Probably works!

**Pull request merged**
